# frozen_string_literal: true

plugins:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'

# Metrics - relaxed for this project
# metrics_calculator.rb has complex data processing methods that are
# intentionally kept together for readability
Metrics/AbcSize:
  Max: 150

Metrics/MethodLength:
  Max: 110

Metrics/ClassLength:
  Max: 450

Metrics/BlockLength:
  Max: 55
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 35

Metrics/PerceivedComplexity:
  Max: 35

Metrics/ParameterLists:
  Max: 6

# Style
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

# RSpec - relaxed settings for aggregate_failures style
RSpec/MultipleExpectations:
  Max: 15

RSpec/ExampleLength:
  Max: 25

RSpec/MultipleMemoizedHelpers:
  Max: 15

RSpec/NestedGroups:
  Max: 5

# Allow expect().to receive() pattern for setting up mocks
RSpec/MessageSpies:
  Enabled: false

# Allow multiple top-level describes for related classes
RSpec/MultipleDescribes:
  Enabled: false

# Allow stubbing subject when testing private methods
RSpec/SubjectStub:
  Enabled: false
